### ISSUE TITLE
"This is not a valid plugin."

### ISSUE THREAD

**Issue by glazanova** [Daniel-KM/Omeka-plugin-ArchiveRepertory#6]
Hi, 
For some reason ArchiveRepertory (we tried versions 2.15.5 and 2.15.3) does not install on our Omeka (2.6.1). We tried it on 2 different running instances, it says:
ArchiveRepertory
This is not a valid plugin.
Any ideas? 
Thank you.

**Comment by Daniel-KM** [comment]
Try to rename the folder as "ArchiveRepertory".
