### ISSUE TITLE
I can't get the anti-download feature to work. 

### ISSUE THREAD

**Issue by jmtanenbaum** [Daniel-KM/Omeka-plugin-ArchiveRepertory#9]
Hi Daniel, I'd be really grateful if you can help me get the anti-download feature to work. I edited both the routes.ini file and the htaccess file and it still isn't working. I'm not sure what I'm doing wrong.

**Comment by Daniel-KM** [comment]
Hi Julia, 
I think it is fixed: there should not be notice or warning sent by the backend with the files, so disable development mode or fix the other plugins that return warning or deprecation notices.
